%define STACK_ALIGNMENT 16
%define ARCH_X86_64 1
%define ARCH_X86_32 0
%define PIC 1
%define UNDERSCORE_PREFIXED 0
%if UNDERSCORE_PREFIXED
%define PREFIX UNDERSCORE_PREFIXED
%endif
%define HAVE_AVX512ICL 1
